// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghakstxearfsffrbkuxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYWtzdHhlYXJmc2ZmcmJrdXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjgwMzIsImV4cCI6MjA2ODEwNDAzMn0.enbsJ67hsF0Fse6EuoETfyZmYgimS9j3R0CyGI1iVDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});